# Generated by Django 4.0.5 on 2022-06-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='başlık bilgisi burada girilir', max_length=100, null=True, verbose_name='başlık giriniz')),
                ('icerik', models.TextField(max_length=1000, null=True, verbose_name='içerik giriniz')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
