# Generated by Django 4.0.5 on 2022-06-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_kategoriler_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['id'], 'verbose_name_plural': 'gönderiler'},
        ),
        migrations.AddField(
            model_name='blog',
            name='kategori',
            field=models.ManyToManyField(null=True, to='blog.kategoriler'),
        ),
        migrations.AlterField(
            model_name='kategoriler',
            name='isim',
            field=models.CharField(max_length=15, verbose_name='Kategoriismi'),
        ),
    ]
