# Generated by Django 4.0.5 on 2022-06-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_options_blog_kategori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='resim',
            field=models.ImageField(default=None, null=True, upload_to='', verbose_name='resim'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='kategori',
            field=models.ManyToManyField(to='blog.kategoriler'),
        ),
    ]
