# Generated by Django 4.0.5 on 2022-06-22 14:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_resim_alter_blog_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='icerik',
            field=ckeditor.fields.RichTextField(max_length=5000, null=True, verbose_name='içerik'),
        ),
    ]
