# Generated by Django 4.0.5 on 2022-06-22 22:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_icerik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=50, null=True, verbose_name='isim')),
                ('soyisim', models.CharField(blank=True, max_length=50, null=True, verbose_name='soyisim')),
                ('email', models.EmailField(help_text='bu alan zorunlu', max_length=254, null=True, verbose_name='email')),
                ('icerik', ckeditor.fields.RichTextField(help_text='bu alanda fikrinizi belirtebilirsiniz', max_length=1000, null=True, verbose_name='yorum')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
    ]
