# Generated by Django 4.0.5 on 2022-06-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_options_blog_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
