# Generated by Django 4.0.5 on 2022-06-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_blog_options_remove_comment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='icerik',
            field=models.TextField(max_length=100, null=True, verbose_name='yorum'),
        ),
    ]
