# Generated by Django 4.0.5 on 2022-06-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_comment_icerik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='icerik',
            field=models.TextField(max_length=1000, null=True, verbose_name='yorum'),
        ),
    ]
